docker:
  as_root: true
  image: andreptb/maven:3.3.9-jdk8
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git tag -a "${tag}" -m "${tag}"
    mvn clean deploy -Psign-artifacts -Psonatype --settings /home/r/settings.xml