decrypt:
  settings.xml: "frames/settings.xml.asc"
  pubring.gpg: "frames/pubring.gpg.asc"
  secring.gpg: "frames/secring.gpg.asc"
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pjcabi --settings ./settings.xml