docker:
  as_root: true
  image: paasmule/java-maven-git-alpine
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    export newSnapshotVersion=`echo ${tag}-SNAPSHOT | perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e'`
            export CHROME_BIN=/usr/bin/google-chrome
            export DISPLAY=:99.0
            sh -e /etc/init.d/xvfb start
            sudo apt-get update
            sudo apt-get install -y libappindicator1 fonts-liberation
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome*.deb
            mvn clean verify
            git checkout master
            mvn versions:set "-DnewVersion=${newSnapshotVersion}"
            git commit -am "prepare next version"
            git checkout __rultor
            mvn versions:set "-DnewVersion=${tag}"
            git commit -am "${tag}"
            mvn clean deploy -Prelease -Psign-artifacts -Psonatype --settings /home/r/settings.xml