docker:
  as_root: true
  image: hanswesterbeek/google-debian-oracle-jdk:8
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    chmod +x ./mvnw
    ./mvnw -N io.takari:maven:wrapper
    ./mvnw clean
    mvn versions:set "-DnewVersion=${tag}"
    git tag -a "${tag}" -m "${tag}"
    mvn clean deploy -Psign-artifacts -Psonatype --settings /home/r/settings.xml