docker:
  as_root: true
  image: paasmule/java-maven-git-alpine
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |
    export newSnapshotVersion=`echo ${tag}-SNAPSHOT | perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e'`
            mvn clean verify
            git checkout master
            mvn versions:set "-DnewVersion=${newSnapshotVersion}"
            git commit -am "prepare next version"
            git checkout __rultor
            mvn versions:set "-DnewVersion=${tag}"
            git commit -am "${tag}"
            mvn clean deploy -Prelease -Psign-artifacts -Psonatype --settings /home/r/settings.xml