branches:
  only:
    - master

language: java
sudo: true
dist: trusty

script: "./mvnw clean test package"

jdk:
  - oraclejdk8

before_install:  
 - chmod +x ./mvnw
 - mvn -N io.takari:maven:wrapper
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0 
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

after_success:
- mvn clean test jacoco:report coveralls:report
- bash <(curl -s https://codecov.io/bash)

